import type { Metadata } from "next";
import SocketManager from "@/components/socket-manager";
import "./globals.css";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full h-full bg-primary">
      <body className="w-full h-full">
        <ThemeProvider>
          <SocketManager>{children}</SocketManager>
        </ThemeProvider>
      </body>
    </html>
  );
}
