import type { Metadata } from "next";
import SocketManager from "@/components/socket-manager";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Toaster } from "@/components/ui/sonner";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full w-full" suppressHydrationWarning>
      <body className="w-full h-full bg-background">
        <ThemeProvider attribute="class" defaultTheme="system">
          <QueryClientProvider client={queryClient}>
            <SocketManager>{children}</SocketManager>
            <Toaster richColors position="top-center" />
          </QueryClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
