services:
  app:
    build:
      context: .       
      target: release    # Use the development stage for hot reloading
    ports:
      - "4000:4000"    

    # env_file:
    #   - ./.env         # Load common dev variables
    #   - ./.env.local   # Load local overrides (and potentially sensitive ones)

    volumes:
      - .:/app
      - /app/node_modules

    # command: 
    #   sh -c "bun install && bun --watch src/index.ts"


  redis:
    image: "redis:latest" 
    ports:
      - "6379:6379" 
    command: redis-server --appendonly yes # Optional: Enable AOF persistence for Redis
    volumes:
      - redis_data:/data # Mount a named volume for Redis data persistence

volumes:
  redis_data: 

